# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ComponentStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'started_at': 'datetime',
        'ended_at': 'datetime',
        'component_id': 'str'
    }

    attribute_map = {
        'status': 'status',
        'started_at': 'started_at',
        'ended_at': 'ended_at',
        'component_id': 'component_id'
    }

    def __init__(self, status=None, started_at=None, ended_at=None, component_id=None):  # noqa: E501
        """ComponentStatus - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._started_at = None
        self._ended_at = None
        self._component_id = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if started_at is not None:
            self.started_at = started_at
        if ended_at is not None:
            self.ended_at = ended_at
        if component_id is not None:
            self.component_id = component_id

    @property
    def status(self):
        """Gets the status of this ComponentStatus.  # noqa: E501


        :return: The status of this ComponentStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ComponentStatus.


        :param status: The status of this ComponentStatus.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def started_at(self):
        """Gets the started_at of this ComponentStatus.  # noqa: E501


        :return: The started_at of this ComponentStatus.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this ComponentStatus.


        :param started_at: The started_at of this ComponentStatus.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def ended_at(self):
        """Gets the ended_at of this ComponentStatus.  # noqa: E501


        :return: The ended_at of this ComponentStatus.  # noqa: E501
        :rtype: datetime
        """
        return self._ended_at

    @ended_at.setter
    def ended_at(self, ended_at):
        """Sets the ended_at of this ComponentStatus.


        :param ended_at: The ended_at of this ComponentStatus.  # noqa: E501
        :type: datetime
        """

        self._ended_at = ended_at

    @property
    def component_id(self):
        """Gets the component_id of this ComponentStatus.  # noqa: E501


        :return: The component_id of this ComponentStatus.  # noqa: E501
        :rtype: str
        """
        return self._component_id

    @component_id.setter
    def component_id(self, component_id):
        """Sets the component_id of this ComponentStatus.


        :param component_id: The component_id of this ComponentStatus.  # noqa: E501
        :type: str
        """

        self._component_id = component_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComponentStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComponentStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
