# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DatasourceBQCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'client_project': 'str',
        'client_dataset': 'str',
        'client_table': 'str',
        'bigquery_type': 'str',
        'service_account': 'object'
    }

    attribute_map = {
        'name': 'name',
        'client_project': 'client_project',
        'client_dataset': 'client_dataset',
        'client_table': 'client_table',
        'bigquery_type': 'bigquery_type',
        'service_account': 'service_account'
    }

    def __init__(self, name=None, client_project=None, client_dataset=None, client_table=None, bigquery_type=None, service_account=None):  # noqa: E501
        """DatasourceBQCreate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._client_project = None
        self._client_dataset = None
        self._client_table = None
        self._bigquery_type = None
        self._service_account = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if client_project is not None:
            self.client_project = client_project
        if client_dataset is not None:
            self.client_dataset = client_dataset
        if client_table is not None:
            self.client_table = client_table
        if bigquery_type is not None:
            self.bigquery_type = bigquery_type
        if service_account is not None:
            self.service_account = service_account

    @property
    def name(self):
        """Gets the name of this DatasourceBQCreate.  # noqa: E501


        :return: The name of this DatasourceBQCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DatasourceBQCreate.


        :param name: The name of this DatasourceBQCreate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def client_project(self):
        """Gets the client_project of this DatasourceBQCreate.  # noqa: E501


        :return: The client_project of this DatasourceBQCreate.  # noqa: E501
        :rtype: str
        """
        return self._client_project

    @client_project.setter
    def client_project(self, client_project):
        """Sets the client_project of this DatasourceBQCreate.


        :param client_project: The client_project of this DatasourceBQCreate.  # noqa: E501
        :type: str
        """

        self._client_project = client_project

    @property
    def client_dataset(self):
        """Gets the client_dataset of this DatasourceBQCreate.  # noqa: E501


        :return: The client_dataset of this DatasourceBQCreate.  # noqa: E501
        :rtype: str
        """
        return self._client_dataset

    @client_dataset.setter
    def client_dataset(self, client_dataset):
        """Sets the client_dataset of this DatasourceBQCreate.


        :param client_dataset: The client_dataset of this DatasourceBQCreate.  # noqa: E501
        :type: str
        """

        self._client_dataset = client_dataset

    @property
    def client_table(self):
        """Gets the client_table of this DatasourceBQCreate.  # noqa: E501


        :return: The client_table of this DatasourceBQCreate.  # noqa: E501
        :rtype: str
        """
        return self._client_table

    @client_table.setter
    def client_table(self, client_table):
        """Sets the client_table of this DatasourceBQCreate.


        :param client_table: The client_table of this DatasourceBQCreate.  # noqa: E501
        :type: str
        """

        self._client_table = client_table

    @property
    def bigquery_type(self):
        """Gets the bigquery_type of this DatasourceBQCreate.  # noqa: E501


        :return: The bigquery_type of this DatasourceBQCreate.  # noqa: E501
        :rtype: str
        """
        return self._bigquery_type

    @bigquery_type.setter
    def bigquery_type(self, bigquery_type):
        """Sets the bigquery_type of this DatasourceBQCreate.


        :param bigquery_type: The bigquery_type of this DatasourceBQCreate.  # noqa: E501
        :type: str
        """

        self._bigquery_type = bigquery_type

    @property
    def service_account(self):
        """Gets the service_account of this DatasourceBQCreate.  # noqa: E501


        :return: The service_account of this DatasourceBQCreate.  # noqa: E501
        :rtype: object
        """
        return self._service_account

    @service_account.setter
    def service_account(self, service_account):
        """Sets the service_account of this DatasourceBQCreate.


        :param service_account: The service_account of this DatasourceBQCreate.  # noqa: E501
        :type: object
        """

        self._service_account = service_account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatasourceBQCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatasourceBQCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
