# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatasourceCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'args': 'object',
        'type': 'str',
        'source': 'str',
        'provider_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'args': 'args',
        'type': 'type',
        'source': 'source',
        'provider_id': 'provider_id'
    }

    def __init__(self, name=None, args=None, type=None, source=None, provider_id=None):  # noqa: E501
        """DatasourceCreate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._args = None
        self._type = None
        self._source = None
        self._provider_id = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if args is not None:
            self.args = args
        if type is not None:
            self.type = type
        if source is not None:
            self.source = source
        if provider_id is not None:
            self.provider_id = provider_id

    @property
    def name(self):
        """Gets the name of this DatasourceCreate.  # noqa: E501


        :return: The name of this DatasourceCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DatasourceCreate.


        :param name: The name of this DatasourceCreate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def args(self):
        """Gets the args of this DatasourceCreate.  # noqa: E501


        :return: The args of this DatasourceCreate.  # noqa: E501
        :rtype: object
        """
        return self._args

    @args.setter
    def args(self, args):
        """Sets the args of this DatasourceCreate.


        :param args: The args of this DatasourceCreate.  # noqa: E501
        :type: object
        """

        self._args = args

    @property
    def type(self):
        """Gets the type of this DatasourceCreate.  # noqa: E501


        :return: The type of this DatasourceCreate.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DatasourceCreate.


        :param type: The type of this DatasourceCreate.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def source(self):
        """Gets the source of this DatasourceCreate.  # noqa: E501


        :return: The source of this DatasourceCreate.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this DatasourceCreate.


        :param source: The source of this DatasourceCreate.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def provider_id(self):
        """Gets the provider_id of this DatasourceCreate.  # noqa: E501


        :return: The provider_id of this DatasourceCreate.  # noqa: E501
        :rtype: str
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id):
        """Sets the provider_id of this DatasourceCreate.


        :param provider_id: The provider_id of this DatasourceCreate.  # noqa: E501
        :type: str
        """

        self._provider_id = provider_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatasourceCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatasourceCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
