# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DatasourceInDB(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'id': 'str',
        'organization_id': 'str',
        'datasource_type': 'str',
        'created_at': 'datetime'
    }

    attribute_map = {
        'name': 'name',
        'id': 'id',
        'organization_id': 'organization_id',
        'datasource_type': 'datasource_type',
        'created_at': 'created_at'
    }

    def __init__(self, name=None, id=None, organization_id=None, datasource_type=None, created_at=None):  # noqa: E501
        """DatasourceInDB - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._id = None
        self._organization_id = None
        self._datasource_type = None
        self._created_at = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if id is not None:
            self.id = id
        if organization_id is not None:
            self.organization_id = organization_id
        if datasource_type is not None:
            self.datasource_type = datasource_type
        if created_at is not None:
            self.created_at = created_at

    @property
    def name(self):
        """Gets the name of this DatasourceInDB.  # noqa: E501


        :return: The name of this DatasourceInDB.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DatasourceInDB.


        :param name: The name of this DatasourceInDB.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this DatasourceInDB.  # noqa: E501


        :return: The id of this DatasourceInDB.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DatasourceInDB.


        :param id: The id of this DatasourceInDB.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def organization_id(self):
        """Gets the organization_id of this DatasourceInDB.  # noqa: E501


        :return: The organization_id of this DatasourceInDB.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this DatasourceInDB.


        :param organization_id: The organization_id of this DatasourceInDB.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def datasource_type(self):
        """Gets the datasource_type of this DatasourceInDB.  # noqa: E501


        :return: The datasource_type of this DatasourceInDB.  # noqa: E501
        :rtype: str
        """
        return self._datasource_type

    @datasource_type.setter
    def datasource_type(self, datasource_type):
        """Sets the datasource_type of this DatasourceInDB.


        :param datasource_type: The datasource_type of this DatasourceInDB.  # noqa: E501
        :type: str
        """

        self._datasource_type = datasource_type

    @property
    def created_at(self):
        """Gets the created_at of this DatasourceInDB.  # noqa: E501


        :return: The created_at of this DatasourceInDB.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this DatasourceInDB.


        :param created_at: The created_at of this DatasourceInDB.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatasourceInDB, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatasourceInDB):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
