# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class MetricInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'cost': 'float',
        'component_metric_id': 'int',
        'service': 'str',
        'usage': 'float',
        'id': 'int'
    }

    attribute_map = {
        'name': 'name',
        'cost': 'cost',
        'component_metric_id': 'component_metric_id',
        'service': 'service',
        'usage': 'usage',
        'id': 'id'
    }

    def __init__(self, name=None, cost=0, component_metric_id=None, service=None, usage=0, id=None):  # noqa: E501
        """MetricInfo - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._cost = None
        self._component_metric_id = None
        self._service = None
        self._usage = None
        self._id = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if cost is not None:
            self.cost = cost
        if component_metric_id is not None:
            self.component_metric_id = component_metric_id
        if service is not None:
            self.service = service
        if usage is not None:
            self.usage = usage
        if id is not None:
            self.id = id

    @property
    def name(self):
        """Gets the name of this MetricInfo.  # noqa: E501


        :return: The name of this MetricInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MetricInfo.


        :param name: The name of this MetricInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def cost(self):
        """Gets the cost of this MetricInfo.  # noqa: E501


        :return: The cost of this MetricInfo.  # noqa: E501
        :rtype: float
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this MetricInfo.


        :param cost: The cost of this MetricInfo.  # noqa: E501
        :type: float
        """

        self._cost = cost

    @property
    def component_metric_id(self):
        """Gets the component_metric_id of this MetricInfo.  # noqa: E501


        :return: The component_metric_id of this MetricInfo.  # noqa: E501
        :rtype: int
        """
        return self._component_metric_id

    @component_metric_id.setter
    def component_metric_id(self, component_metric_id):
        """Sets the component_metric_id of this MetricInfo.


        :param component_metric_id: The component_metric_id of this MetricInfo.  # noqa: E501
        :type: int
        """

        self._component_metric_id = component_metric_id

    @property
    def service(self):
        """Gets the service of this MetricInfo.  # noqa: E501


        :return: The service of this MetricInfo.  # noqa: E501
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this MetricInfo.


        :param service: The service of this MetricInfo.  # noqa: E501
        :type: str
        """

        self._service = service

    @property
    def usage(self):
        """Gets the usage of this MetricInfo.  # noqa: E501


        :return: The usage of this MetricInfo.  # noqa: E501
        :rtype: float
        """
        return self._usage

    @usage.setter
    def usage(self, usage):
        """Sets the usage of this MetricInfo.


        :param usage: The usage of this MetricInfo.  # noqa: E501
        :type: float
        """

        self._usage = usage

    @property
    def id(self):
        """Gets the id of this MetricInfo.  # noqa: E501


        :return: The id of this MetricInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MetricInfo.


        :param id: The id of this MetricInfo.  # noqa: E501
        :type: int
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetricInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetricInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
