# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PasswordReset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'oob_code': 'str',
        'new_password': 'str'
    }

    attribute_map = {
        'email': 'email',
        'oob_code': 'oob_code',
        'new_password': 'new_password'
    }

    def __init__(self, email=None, oob_code=None, new_password=None):  # noqa: E501
        """PasswordReset - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._oob_code = None
        self._new_password = None
        self.discriminator = None
        self.email = email
        self.oob_code = oob_code
        self.new_password = new_password

    @property
    def email(self):
        """Gets the email of this PasswordReset.  # noqa: E501


        :return: The email of this PasswordReset.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this PasswordReset.


        :param email: The email of this PasswordReset.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def oob_code(self):
        """Gets the oob_code of this PasswordReset.  # noqa: E501


        :return: The oob_code of this PasswordReset.  # noqa: E501
        :rtype: str
        """
        return self._oob_code

    @oob_code.setter
    def oob_code(self, oob_code):
        """Sets the oob_code of this PasswordReset.


        :param oob_code: The oob_code of this PasswordReset.  # noqa: E501
        :type: str
        """
        if oob_code is None:
            raise ValueError("Invalid value for `oob_code`, must not be `None`")  # noqa: E501

        self._oob_code = oob_code

    @property
    def new_password(self):
        """Gets the new_password of this PasswordReset.  # noqa: E501


        :return: The new_password of this PasswordReset.  # noqa: E501
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password):
        """Sets the new_password of this PasswordReset.


        :param new_password: The new_password of this PasswordReset.  # noqa: E501
        :type: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501

        self._new_password = new_password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PasswordReset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PasswordReset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
