# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PipelineRunStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'started_at': 'datetime',
        'ended_at': 'datetime',
        'component_statuses': 'list[ComponentStatus]'
    }

    attribute_map = {
        'status': 'status',
        'started_at': 'started_at',
        'ended_at': 'ended_at',
        'component_statuses': 'component_statuses'
    }

    def __init__(self, status=None, started_at=None, ended_at=None, component_statuses=None):  # noqa: E501
        """PipelineRunStatus - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._started_at = None
        self._ended_at = None
        self._component_statuses = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if started_at is not None:
            self.started_at = started_at
        if ended_at is not None:
            self.ended_at = ended_at
        if component_statuses is not None:
            self.component_statuses = component_statuses

    @property
    def status(self):
        """Gets the status of this PipelineRunStatus.  # noqa: E501


        :return: The status of this PipelineRunStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PipelineRunStatus.


        :param status: The status of this PipelineRunStatus.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def started_at(self):
        """Gets the started_at of this PipelineRunStatus.  # noqa: E501


        :return: The started_at of this PipelineRunStatus.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this PipelineRunStatus.


        :param started_at: The started_at of this PipelineRunStatus.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def ended_at(self):
        """Gets the ended_at of this PipelineRunStatus.  # noqa: E501


        :return: The ended_at of this PipelineRunStatus.  # noqa: E501
        :rtype: datetime
        """
        return self._ended_at

    @ended_at.setter
    def ended_at(self, ended_at):
        """Sets the ended_at of this PipelineRunStatus.


        :param ended_at: The ended_at of this PipelineRunStatus.  # noqa: E501
        :type: datetime
        """

        self._ended_at = ended_at

    @property
    def component_statuses(self):
        """Gets the component_statuses of this PipelineRunStatus.  # noqa: E501


        :return: The component_statuses of this PipelineRunStatus.  # noqa: E501
        :rtype: list[ComponentStatus]
        """
        return self._component_statuses

    @component_statuses.setter
    def component_statuses(self, component_statuses):
        """Sets the component_statuses of this PipelineRunStatus.


        :param component_statuses: The component_statuses of this PipelineRunStatus.  # noqa: E501
        :type: list[ComponentStatus]
        """

        self._component_statuses = component_statuses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PipelineRunStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelineRunStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
