# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PipelineRun(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'workers': 'int',
        'cpus_per_worker': 'int',
        'datasource_commit_id': 'str',
        'run_config': 'object',
        'pipeline_run_type': 'str',
        'id': 'str',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'status': 'str',
        'orchestrator_metadata': 'object',
        'pipeline_id': 'str',
        'user_id': 'str',
        'access_token': 'str',
        'pipeline_components': 'list[PipelineComponent]'
    }

    attribute_map = {
        'workers': 'workers',
        'cpus_per_worker': 'cpus_per_worker',
        'datasource_commit_id': 'datasource_commit_id',
        'run_config': 'run_config',
        'pipeline_run_type': 'pipeline_run_type',
        'id': 'id',
        'start_time': 'start_time',
        'end_time': 'end_time',
        'status': 'status',
        'orchestrator_metadata': 'orchestrator_metadata',
        'pipeline_id': 'pipeline_id',
        'user_id': 'user_id',
        'access_token': 'access_token',
        'pipeline_components': 'pipeline_components'
    }

    def __init__(self, workers=None, cpus_per_worker=None, datasource_commit_id=None, run_config=None, pipeline_run_type=None, id=None, start_time=None, end_time=None, status=None, orchestrator_metadata=None, pipeline_id=None, user_id=None, access_token=None, pipeline_components=None):  # noqa: E501
        """PipelineRun - a model defined in Swagger"""  # noqa: E501
        self._workers = None
        self._cpus_per_worker = None
        self._datasource_commit_id = None
        self._run_config = None
        self._pipeline_run_type = None
        self._id = None
        self._start_time = None
        self._end_time = None
        self._status = None
        self._orchestrator_metadata = None
        self._pipeline_id = None
        self._user_id = None
        self._access_token = None
        self._pipeline_components = None
        self.discriminator = None
        if workers is not None:
            self.workers = workers
        if cpus_per_worker is not None:
            self.cpus_per_worker = cpus_per_worker
        if datasource_commit_id is not None:
            self.datasource_commit_id = datasource_commit_id
        if run_config is not None:
            self.run_config = run_config
        if pipeline_run_type is not None:
            self.pipeline_run_type = pipeline_run_type
        if id is not None:
            self.id = id
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if status is not None:
            self.status = status
        if orchestrator_metadata is not None:
            self.orchestrator_metadata = orchestrator_metadata
        if pipeline_id is not None:
            self.pipeline_id = pipeline_id
        if user_id is not None:
            self.user_id = user_id
        if access_token is not None:
            self.access_token = access_token
        if pipeline_components is not None:
            self.pipeline_components = pipeline_components

    @property
    def workers(self):
        """Gets the workers of this PipelineRun.  # noqa: E501


        :return: The workers of this PipelineRun.  # noqa: E501
        :rtype: int
        """
        return self._workers

    @workers.setter
    def workers(self, workers):
        """Sets the workers of this PipelineRun.


        :param workers: The workers of this PipelineRun.  # noqa: E501
        :type: int
        """

        self._workers = workers

    @property
    def cpus_per_worker(self):
        """Gets the cpus_per_worker of this PipelineRun.  # noqa: E501


        :return: The cpus_per_worker of this PipelineRun.  # noqa: E501
        :rtype: int
        """
        return self._cpus_per_worker

    @cpus_per_worker.setter
    def cpus_per_worker(self, cpus_per_worker):
        """Sets the cpus_per_worker of this PipelineRun.


        :param cpus_per_worker: The cpus_per_worker of this PipelineRun.  # noqa: E501
        :type: int
        """

        self._cpus_per_worker = cpus_per_worker

    @property
    def datasource_commit_id(self):
        """Gets the datasource_commit_id of this PipelineRun.  # noqa: E501


        :return: The datasource_commit_id of this PipelineRun.  # noqa: E501
        :rtype: str
        """
        return self._datasource_commit_id

    @datasource_commit_id.setter
    def datasource_commit_id(self, datasource_commit_id):
        """Sets the datasource_commit_id of this PipelineRun.


        :param datasource_commit_id: The datasource_commit_id of this PipelineRun.  # noqa: E501
        :type: str
        """

        self._datasource_commit_id = datasource_commit_id

    @property
    def run_config(self):
        """Gets the run_config of this PipelineRun.  # noqa: E501


        :return: The run_config of this PipelineRun.  # noqa: E501
        :rtype: object
        """
        return self._run_config

    @run_config.setter
    def run_config(self, run_config):
        """Sets the run_config of this PipelineRun.


        :param run_config: The run_config of this PipelineRun.  # noqa: E501
        :type: object
        """

        self._run_config = run_config

    @property
    def pipeline_run_type(self):
        """Gets the pipeline_run_type of this PipelineRun.  # noqa: E501


        :return: The pipeline_run_type of this PipelineRun.  # noqa: E501
        :rtype: str
        """
        return self._pipeline_run_type

    @pipeline_run_type.setter
    def pipeline_run_type(self, pipeline_run_type):
        """Sets the pipeline_run_type of this PipelineRun.


        :param pipeline_run_type: The pipeline_run_type of this PipelineRun.  # noqa: E501
        :type: str
        """

        self._pipeline_run_type = pipeline_run_type

    @property
    def id(self):
        """Gets the id of this PipelineRun.  # noqa: E501


        :return: The id of this PipelineRun.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PipelineRun.


        :param id: The id of this PipelineRun.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def start_time(self):
        """Gets the start_time of this PipelineRun.  # noqa: E501


        :return: The start_time of this PipelineRun.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this PipelineRun.


        :param start_time: The start_time of this PipelineRun.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this PipelineRun.  # noqa: E501


        :return: The end_time of this PipelineRun.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this PipelineRun.


        :param end_time: The end_time of this PipelineRun.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def status(self):
        """Gets the status of this PipelineRun.  # noqa: E501


        :return: The status of this PipelineRun.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PipelineRun.


        :param status: The status of this PipelineRun.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def orchestrator_metadata(self):
        """Gets the orchestrator_metadata of this PipelineRun.  # noqa: E501


        :return: The orchestrator_metadata of this PipelineRun.  # noqa: E501
        :rtype: object
        """
        return self._orchestrator_metadata

    @orchestrator_metadata.setter
    def orchestrator_metadata(self, orchestrator_metadata):
        """Sets the orchestrator_metadata of this PipelineRun.


        :param orchestrator_metadata: The orchestrator_metadata of this PipelineRun.  # noqa: E501
        :type: object
        """

        self._orchestrator_metadata = orchestrator_metadata

    @property
    def pipeline_id(self):
        """Gets the pipeline_id of this PipelineRun.  # noqa: E501


        :return: The pipeline_id of this PipelineRun.  # noqa: E501
        :rtype: str
        """
        return self._pipeline_id

    @pipeline_id.setter
    def pipeline_id(self, pipeline_id):
        """Sets the pipeline_id of this PipelineRun.


        :param pipeline_id: The pipeline_id of this PipelineRun.  # noqa: E501
        :type: str
        """

        self._pipeline_id = pipeline_id

    @property
    def user_id(self):
        """Gets the user_id of this PipelineRun.  # noqa: E501


        :return: The user_id of this PipelineRun.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this PipelineRun.


        :param user_id: The user_id of this PipelineRun.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def access_token(self):
        """Gets the access_token of this PipelineRun.  # noqa: E501


        :return: The access_token of this PipelineRun.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this PipelineRun.


        :param access_token: The access_token of this PipelineRun.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def pipeline_components(self):
        """Gets the pipeline_components of this PipelineRun.  # noqa: E501


        :return: The pipeline_components of this PipelineRun.  # noqa: E501
        :rtype: list[PipelineComponent]
        """
        return self._pipeline_components

    @pipeline_components.setter
    def pipeline_components(self, pipeline_components):
        """Sets the pipeline_components of this PipelineRun.


        :param pipeline_components: The pipeline_components of this PipelineRun.  # noqa: E501
        :type: list[PipelineComponent]
        """

        self._pipeline_components = pipeline_components

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PipelineRun, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelineRun):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
