# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PipelineUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'env_config': 'object',
        'exp_config': 'object',
        'workspace_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'env_config': 'env_config',
        'exp_config': 'exp_config',
        'workspace_id': 'workspace_id'
    }

    def __init__(self, name=None, env_config=None, exp_config=None, workspace_id=None):  # noqa: E501
        """PipelineUpdate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._env_config = None
        self._exp_config = None
        self._workspace_id = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if env_config is not None:
            self.env_config = env_config
        if exp_config is not None:
            self.exp_config = exp_config
        if workspace_id is not None:
            self.workspace_id = workspace_id

    @property
    def name(self):
        """Gets the name of this PipelineUpdate.  # noqa: E501


        :return: The name of this PipelineUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PipelineUpdate.


        :param name: The name of this PipelineUpdate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def env_config(self):
        """Gets the env_config of this PipelineUpdate.  # noqa: E501


        :return: The env_config of this PipelineUpdate.  # noqa: E501
        :rtype: object
        """
        return self._env_config

    @env_config.setter
    def env_config(self, env_config):
        """Sets the env_config of this PipelineUpdate.


        :param env_config: The env_config of this PipelineUpdate.  # noqa: E501
        :type: object
        """

        self._env_config = env_config

    @property
    def exp_config(self):
        """Gets the exp_config of this PipelineUpdate.  # noqa: E501


        :return: The exp_config of this PipelineUpdate.  # noqa: E501
        :rtype: object
        """
        return self._exp_config

    @exp_config.setter
    def exp_config(self, exp_config):
        """Sets the exp_config of this PipelineUpdate.


        :param exp_config: The exp_config of this PipelineUpdate.  # noqa: E501
        :type: object
        """

        self._exp_config = exp_config

    @property
    def workspace_id(self):
        """Gets the workspace_id of this PipelineUpdate.  # noqa: E501


        :return: The workspace_id of this PipelineUpdate.  # noqa: E501
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this PipelineUpdate.


        :param workspace_id: The workspace_id of this PipelineUpdate.  # noqa: E501
        :type: str
        """

        self._workspace_id = workspace_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PipelineUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelineUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
