# coding: utf-8

"""
    maiot Core Engine API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserInOrganization(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'full_name': 'str',
        'organization_id': 'str',
        'n_pipelines_executed': 'int',
        'firebase_id': 'str',
        'id': 'str',
        'created_at': 'datetime',
        'role_id': 'str',
        'role': 'str'
    }

    attribute_map = {
        'email': 'email',
        'full_name': 'full_name',
        'organization_id': 'organization_id',
        'n_pipelines_executed': 'n_pipelines_executed',
        'firebase_id': 'firebase_id',
        'id': 'id',
        'created_at': 'created_at',
        'role_id': 'role_id',
        'role': 'role'
    }

    def __init__(self, email=None, full_name=None, organization_id=None, n_pipelines_executed=0, firebase_id=None, id=None, created_at=None, role_id=None, role=None):  # noqa: E501
        """UserInOrganization - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._full_name = None
        self._organization_id = None
        self._n_pipelines_executed = None
        self._firebase_id = None
        self._id = None
        self._created_at = None
        self._role_id = None
        self._role = None
        self.discriminator = None
        if email is not None:
            self.email = email
        if full_name is not None:
            self.full_name = full_name
        if organization_id is not None:
            self.organization_id = organization_id
        if n_pipelines_executed is not None:
            self.n_pipelines_executed = n_pipelines_executed
        if firebase_id is not None:
            self.firebase_id = firebase_id
        if id is not None:
            self.id = id
        if created_at is not None:
            self.created_at = created_at
        if role_id is not None:
            self.role_id = role_id
        if role is not None:
            self.role = role

    @property
    def email(self):
        """Gets the email of this UserInOrganization.  # noqa: E501


        :return: The email of this UserInOrganization.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserInOrganization.


        :param email: The email of this UserInOrganization.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def full_name(self):
        """Gets the full_name of this UserInOrganization.  # noqa: E501


        :return: The full_name of this UserInOrganization.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this UserInOrganization.


        :param full_name: The full_name of this UserInOrganization.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def organization_id(self):
        """Gets the organization_id of this UserInOrganization.  # noqa: E501


        :return: The organization_id of this UserInOrganization.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this UserInOrganization.


        :param organization_id: The organization_id of this UserInOrganization.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def n_pipelines_executed(self):
        """Gets the n_pipelines_executed of this UserInOrganization.  # noqa: E501


        :return: The n_pipelines_executed of this UserInOrganization.  # noqa: E501
        :rtype: int
        """
        return self._n_pipelines_executed

    @n_pipelines_executed.setter
    def n_pipelines_executed(self, n_pipelines_executed):
        """Sets the n_pipelines_executed of this UserInOrganization.


        :param n_pipelines_executed: The n_pipelines_executed of this UserInOrganization.  # noqa: E501
        :type: int
        """

        self._n_pipelines_executed = n_pipelines_executed

    @property
    def firebase_id(self):
        """Gets the firebase_id of this UserInOrganization.  # noqa: E501


        :return: The firebase_id of this UserInOrganization.  # noqa: E501
        :rtype: str
        """
        return self._firebase_id

    @firebase_id.setter
    def firebase_id(self, firebase_id):
        """Sets the firebase_id of this UserInOrganization.


        :param firebase_id: The firebase_id of this UserInOrganization.  # noqa: E501
        :type: str
        """

        self._firebase_id = firebase_id

    @property
    def id(self):
        """Gets the id of this UserInOrganization.  # noqa: E501


        :return: The id of this UserInOrganization.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserInOrganization.


        :param id: The id of this UserInOrganization.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this UserInOrganization.  # noqa: E501


        :return: The created_at of this UserInOrganization.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this UserInOrganization.


        :param created_at: The created_at of this UserInOrganization.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def role_id(self):
        """Gets the role_id of this UserInOrganization.  # noqa: E501


        :return: The role_id of this UserInOrganization.  # noqa: E501
        :rtype: str
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id):
        """Sets the role_id of this UserInOrganization.


        :param role_id: The role_id of this UserInOrganization.  # noqa: E501
        :type: str
        """

        self._role_id = role_id

    @property
    def role(self):
        """Gets the role of this UserInOrganization.  # noqa: E501


        :return: The role of this UserInOrganization.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this UserInOrganization.


        :param role: The role of this UserInOrganization.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserInOrganization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserInOrganization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
